
-- 1. Create the Officers Table
CREATE TABLE public.officers (
    id text PRIMARY KEY,
    name text NOT NULL,
    role text DEFAULT 'BDO',
    status text DEFAULT 'Offline',
    lat double precision,
    lng double precision,
    battery integer DEFAULT 100,
    signal_strength integer DEFAULT 100,
    network_type text DEFAULT '5G',
    last_update timestamp with time zone DEFAULT timezone('utc'::text, now()),
    avatar text,
    telemetry_source text DEFAULT 'WEB',
    app_version text,
    pipeline_value numeric DEFAULT 0,
    visit_count integer DEFAULT 0,
    quota_progress integer DEFAULT 0,
    tasks jsonb DEFAULT '[]'::jsonb,
    leads jsonb DEFAULT '[]'::jsonb
);

-- 2. Create History Table
CREATE TABLE public.location_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text REFERENCES public.officers(id) ON DELETE CASCADE,
    lat double precision,
    lng double precision,
    battery integer,
    status text,
    timestamp timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. Create Messages Table
CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    text text NOT NULL,
    sender_id text NOT NULL,
    sender_name text NOT NULL,
    is_from_admin boolean DEFAULT false,
    is_directive boolean DEFAULT false,
    timestamp timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. Create Incidents Table
CREATE TABLE public.incidents (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    description text,
    severity text DEFAULT 'info',
    reported_by text,
    lat double precision,
    lng double precision,
    timestamp timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 5. Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.officers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.incidents;

-- 6. RLS Policies
ALTER TABLE public.officers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

-- Allow public access for this demo app (In prod, use 'authenticated')
CREATE POLICY "Public Access Officers" ON public.officers FOR ALL USING (true);
CREATE POLICY "Public Access History" ON public.location_history FOR ALL USING (true);
CREATE POLICY "Public Access Messages" ON public.messages FOR ALL USING (true);
CREATE POLICY "Public Access Incidents" ON public.incidents FOR ALL USING (true);

-- Seed Admin
INSERT INTO public.officers (id, name, role, status)
VALUES ('ADM-ROOT', 'System Administrator', 'Admin', 'Active')
ON CONFLICT (id) DO NOTHING;
